
- name: prepare all LXC containers
  hosts: all
  tasks:
    - name: install packages
      become: yes
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - dnsutils
        - netcat-openbsd

    - name: add aliases to bashrc
      lineinfile:
        path: ~/.bash_aliases
        create: yes
        line: "{{ item }}"
        insertafter: alias.*
      loop:
        - "alias l='ls -lish'"
        - "alias ll='ls -lisah'"
        - "alias s='sudo'"
        - "alias sctl='sudo systemctl'"
